all:
	javac CustomException.java
	javac ListNodeInterface.java
	javac ListNode.java
	javac LinkedListInterface.java
	javac LinkedList.java
	javac Main.java
	java Main
node:
	javac CustomException.java
	javac ListNodeInterface.java
	javac ListNode.java
	javac CheckNode.java
	java CheckNode
list:
	javac CustomException.java
	javac ListNodeInterface.java
	javac ListNode.java
	javac LinkedListInterface.java
	javac LinkedList.java
	javac CheckLL.java
	java CheckLL
clean:
	rm *.class
