all:
	javac CustomException.java
	javac ListNodeInterface.java
	javac ListNode.java
	javac LinkedListInterface.java
	javac LinkedList.java
	javac Main.java
	java Main
node:
	javac CustomException.java
	javac ListNodeInterface.java
	javac ListNode.java
	javac CheckNode.java
	java CheckNode
list:
	javac CustomException.java
	javac ListNodeInterface.java
	javac ListNode.java
	javac LinkedListInterface.java
	javac LinkedList.java
	javac CheckLL.java
	java CheckLL
stack:
	javac CustomException.java
	javac ListNodeInterface.java
	javac ListNode.java
	javac LinkedListInterface.java
	javac LinkedList.java
	javac StackInterfaceL.java
	javac StackL.java
	javac CheckSLL.java
	java CheckSLL
clean:
	rm *.class
